<?php
return [
    "dishes" => [
        [
            "name" => "patatine fritte",
            "price" => "2.90",
            "visible" => 1,
            "ingredients" => "patatine, sale, olio di semi di arachide",
            "image" => "img/patatine fritte.png",
            "restaurant_id" => [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
            "category_id" => 11,
        ],
        [
            "name" => "bacon burger",
            "price" => "7.10",
            "visible" => 1,
            "ingredients" => "pane, bacon, hamburger, cheddar, maionese, ketchup",
            "image" => "img/bacon burger.png",
            "restaurant_id" => [4],
            "category_id" => 8,
        ],
        [
            "name" => "margherita",
            "price" => "5.50",
            "visible" => 1,
            "ingredients" => "salsa di pomodoro, mozzarella, basilico",
            "image" => "img/margherita.png",
            "restaurant_id" => [1],
            "category_id" => 7,
        ],
        [
            "name" => "napoli",
            "price" => "8.50",
            "visible" => 1,
            "ingredients" => "salsa di pomodoro, mozzarella, acciughe sott'olio, olio, origano",
            "image" => "img/napoli.png",
            "restaurant_id" => [1],
            "category_id" => 7,
        ],
        [
            "name" => "quattro stagioni",
            "price" => "8.00",
            "visible" => 1,
            "ingredients" => "salsa di pomodoro, mozzarella, funghi, carciofi, peperoni, prosciutto cotto",
            "image" => "img/quattro stagioni.png",
            "restaurant_id" => [1],
            "category_id" => 7,
        ],
        [
            "name" => "spaziale",
            "price" => "9.00",
            "visible" => 1,
            "ingredients" => "salsa di pomodoro, mozzarella, patate lesse, gorgonzola, pancetta in cottura, olio, origano",
            "image" => "img/spaziale.png",
            "restaurant_id" => [1],
            "category_id" => 7,
        ],
        [
            "name" => "cornetti pizza",
            "price" => "7.50",
            "visible" => 1,
            "ingredients" => "salsa di pomodoro, mozzarella, olio",
            "image" => "img/cornetti pizza.png",
            "restaurant_id" => [1],
            "category_id" => 7,
        ],
        [
            "name" => "pizzaiola",
            "price" => "8.00",
            "visible" => 1,
            "ingredients" => "salsa di pomodoro, mozzarella, aglio, acciughe, peperoncino, olive, origano",
            "image" => "img/pizzaiola.png",
            "restaurant_id" => [1],
            "category_id" => 7,
        ],
        [
            "name" => "cotechino con lenticchie",
            "price" => "18.00",
            "visible" => 1,
            "ingredients" => "cotechino, lenticchie, carote, olio, rosmarino, sale, sedano cipolle, alloro",
            "image" => "img/cotechino con lenticchie.png",
            "restaurant_id" => [5],
            "category_id" => 3,
        ],
        [
            "name" => "chili con carne",
            "price" => "8.90",
            "visible" => 1,
            "ingredients" => "manzo, peperoni rossi, brodo di carne, cipolle rosse, peperoncino fresco, cumino, zucchero di canna, fagioli, passata di pomodoro, cipolle",
            "image" => "img/chili con carne.png",
            "restaurant_id" => [7],
            "category_id" => 3,
        ],
        [
            "name" => "paella de marisco",
            "price" => "15.60",
            "visible" => 1,
            "ingredients" => "riso bomba, calamari, gamberi, aglio, paprika, passata di pomodoro, olio, pepe, cozze, scampi, cipolle, fumetto di crostacei, zafferano, peperoncini",
            "image" => "img/paella de marisco.png",
            "restaurant_id" => [6],
            "category_id" => 4,
        ],
        [
            "name" => "uramaki di sushi",
            "price" => "7.50",
            "visible" => 1,
            "ingredients" => "salmone, tonno, riso nishiki, aceto di riso, zucchero, acqua, sale, alga kombu",
            "image" => "img/uramaki di sushi.png",
            "restaurant_id" => [3],
            "category_id" => 4,
        ],
        [
            "name" => "zuppa di pesce",
            "price" => "14.90",
            "visible" => 1,
            "ingredients" => "gamberi, gallinella, triglie, aglio, vino bianco, pepe, seppie, coda di rospo, olio, prezzemolo",
            "image" => "img/zuppa di pesce.png",
            "restaurant_id" => [2],
            "category_id" => 4,
        ],
        [
            "name" => "spaghetti di riso con verdure",
            "price" => "8.50",
            "visible" => 1,
            "ingredients" => "spaghetti di riso, zucchine, cipolle, olio, salsa di soia, pepe bianco, carota, sale",
            "image" => "img/spaghetti di riso con verdure.png",
            "restaurant_id" => [2],
            "category_id" => 2,
        ],
        [
            "name" => "parmigiana di patate",
            "price" => "11.00",
            "visible" => 1,
            "ingredients" => "patate, provola, sale, grana, pepe, besciamella",
            "image" => "img/parmigiana di patate.png",
            "restaurant_id" => [5],
            "category_id" => 2,
        ],
        [
            "name" => "fajitas",
            "price" => "5.00",
            "visible" => 1,
            "ingredients" => "tortillas, guacamole, controfiletto di manzo, peperoni rossi, cipolle bianche, worcestershire sauce, cumino, sale, petto di pollo, peperoni, lime, coriandolo, olio",
            "image" => "img/fajitas.png",
            "restaurant_id" => [10],
            "category_id" => 9,
        ],
        [
            "name" => "ramen",
            "price" => "9.00",
            "visible" => 1,
            "ingredients" => "noodles, brodo(acqua, pancia di maiale, zenzero, aglio, katsuobushi, alga kombu, cipollotto), carne di maiale(cotta con tamari, mirin, sake, zenzero, aglio), uovo marinato, cipolle dorate",
            "image" => "img/ramen.png",
            "restaurant_id" => [3],
            "category_id" => 3,
        ],
        [
            "name" => "burrito",
            "price" => "9.00",
            "visible" => 1,
            "ingredients" => "tortilla, macinato di manzo, peperoni rossi, brodo di carne, aglio, coriandolo in polvere, fagioli neri, cipolle rosse, pepe, avocado, lime, mais",
            "image" => "img/burrito.png",
            "restaurant_id" => [7],
            "category_id" => 9,
        ],
        [
            "name" => "empanadas",
            "price" => "7.30",
            "visible" => 1,
            "ingredients" => "impasto, carne bovina, peperoni rossi, olive, strutto, origano, pepe, uova sode, cipolle ramate, cumino",
            "image" => "img/empanadas.png",
            "restaurant_id" => [7],
            "category_id" => 3,
        ],
        [
            "name" => "couscous",
            "price" => "12.10",
            "visible" => 1,
            "ingredients" => "cous cous, brodo vegetale, olio, peperoni rossi, pisellini, pepe, paprika, olio, zucchine, carote, scalogno, scorza di limone",
            "image" => "img/couscous.png",
            "restaurant_id" => [10],
            "category_id" => 2,
        ],
        [
            "name" => "tacos",
            "price" => "8.40",
            "visible" => 1,
            "ingredients" => "tacos, peperoncino dolce, salsiccia, concentrato di pomodore, pepe, pomodori, prezzemolo, olio, cipollotto, panna acida, yogurt",
            "image" => "img/tacos.png",
            "restaurant_id" => [7],
            "category_id" => 9,
        ],
        [
            "name" => "pollo tika masala",
            "price" => "15.50",
            "visible" => 1,
            "ingredients" => "petto di pollo, yogurt greco, garam masala, aglio, sale, zenzero, paprika, panna, aglio, cumino, curcuma",
            "image" => "img/pollo tika masala.png",
            "restaurant_id" => [8],
            "category_id" => 3,
        ],
        [
            "name" => "nachos",
            "price" => "14.30",
            "visible" => 1,
            "ingredients" => "tortillas, peperoncini jalapeno, edamer, olio",
            "image" => "img/nachos.png",
            "restaurant_id" => [7],
            "category_id" => 1,
        ],
        [
            "name" => "baozi",
            "price" => "15.00",
            "visible" => 1,
            "ingredients" => "impasto di farina, maiale, cipollotto, salsa di soia, olio, pepe, cavolo, zenzero, sale",
            "image" => "img/baozi.png",
            "restaurant_id" => [2],
            "category_id" => 2,
        ],
        [
            "name" => "coca-cola",
            "price" => "3.50",
            "visible" => 1,
            "ingredients" => "acqua gassata (o acqua e anidride carbonica), zucchero (saccarosio o sciroppo di saccarosio o sciroppo di mais ad alto contenuto di fruttosio), caffeina, acido fosforico, colorante caramello (E150d), glicerina ed aromi naturali",
            "image" => "img/coca-cola.png",
            "restaurant_id" => [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11],
            "category_id" => 12,
        ],
        [
            "name" => "fanta",
            "price" => "3.20",
            "visible" => 1,
            "ingredients" => "acqua, succo di arancia (12%), zucchero, anidride carbonica, acidificante acido citrico, aromi naturali di agrumi, stabilizzante gomma d'acacia, antiossidante acido ascorbico.",
            "image" => "img/fanta.png",
            "restaurant_id" => [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11],
            "category_id" => 12,
        ],
        [
            "name" => "sprite",
            "price" => "3.80",
            "visible" => 1,
            "ingredients" => "acqua, zucchero, anidride carbonica, acidificante acido citrico, edulcoranti acesulfame K, aspartame e neoesperidina DC, correttore di acidità citrato trisodico, aromi naturali  ",
            "image" => "img/sprite.png",
            "restaurant_id" => [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11],
            "category_id" => 12,
        ],
        [
            "name" => "the al limone",
            "price" => "4.20",
            "visible" => 1,
            "ingredients" => " acqua, zucchero, correttori di acidità: acido citrico e citrato di potassio, estratto di tè (0,1%), succo di limone (0,1%), antiossidanti: acido ascorbico, aromi naturali.",
            "image" => "img/te al limone.png",
            "restaurant_id" => [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11],
            "category_id" => 12,
        ],
        [
            "name" => "the alla pesca",
            "price" => "4.20",
            "visible" => 1,
            "ingredients" => " acqua, zucchero, correttori di acidità: acido citrico e citrato di potassio, estratto di tè (0,1%), succo di pesca (0,1%), antiossidanti: acido ascorbico, aromi naturali.",
            "image" => "img/te alla pesca.png",
            "restaurant_id" => [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11],
            "category_id" => 12,
        ],
        [
            "name" => "birra",
            "price" => "5.80",
            "visible" => 1,
            "ingredients" => "acqua, malto, lievito, luppolo",
            "image" => "img/birra.png",
            "restaurant_id" => [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11],
            "category_id" => 12,
        ],
        [
            "name" => "poke vegano",
            "price" => "12.80",
            "visible" => 1,
            "ingredients" => "avocado, fagioli atzuki, miglio, cetriolo, carote e zucchine alla julienne",
            "image" => "img/poke.jpg",
            "restaurant_id" => [11],
            "category_id" => 2,
        ],
        [
            "name" => "tofu",
            "price" => "18.80",
            "visible" => 1,
            "ingredients" => "soia",
            "image" => "img/tofu.png",
            "restaurant_id" => [11],
            "category_id" => 2,
        ],
        [
            "name" => "kebab arrotolato",
            "price" => "8.80",
            "visible" => 1,
            "ingredients" => "piadina, carne di agnello, salsa piccante, cipolla",
            "image" => "img/kebab.jpg",
            "restaurant_id" => [9],
            "category_id" => 2,
        ],
        [
            "name" => "falafel",
            "price" => "6.50",
            "visible" => 1,
            "ingredients" => "ceci, aglio, cumino, cipolle, salsa allo yogurt",
            "image" => "img/falafel.jpg",
            "restaurant_id" => [9],
            "category_id" => 2,
        ],
        [
            "name" => "tiramisu",
            "price" => "12.00",
            "visible" => 1,
            "ingredients" => "cacao in polvere, mascarpone, caffè, savoiardi",
            "image" => "img/tiramisu.jpg",
            "restaurant_id" => [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
            "category_id" => 2,
        ],
        [
            "name" => "profiteroles",
            "price" => "10.00",
            "visible" => 1,
            "ingredients" => "latte, burro, farina, cioccolato, panna",
            "image" => "img/profiteroles.jpg",
            "restaurant_id" => [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
            "category_id" => 2,
        ],
        [
            "name" => "biscotto della fortuna",
            "price" => "2.00",
            "visible" => 1,
            "ingredients" => "zucchero, albumi, farina di riso, amido di mais, farina tipo 00",
            "image" => "img/biscotto-della-fortuna.jpg",
            "restaurant_id" => [2],
            "category_id" => 2,
        ],
        [
            "name" => "torta della luna",
            "price" => "2.50",
            "visible" => 1,
            "ingredients" => "latte, burro, farina, cioccolato, panna",
            "image" => "img/torta-della-luna.jpg",
            "restaurant_id" => [2],
            "category_id" => 2,
        ],
        [
            "name" => "mochi",
            "price" => "2.00",
            "visible" => 1,
            "ingredients" => "zucchero, albumi, farina di riso, amido di mais, farina tipo 00",
            "image" => "img/mochi.jpg",
            "restaurant_id" => [3],
            "category_id" => 2,
        ],
        [
            "name" => "dorayaki",
            "price" => "4.50",
            "visible" => 1,
            "ingredients" => "latte, burro, farina, cioccolato, panna",
            "image" => "img/dorayaki.jpg",
            "restaurant_id" => [3],
            "category_id" => 2,
        ],
        [
            "name" => "cheesecake",
            "price" => "11.00",
            "visible" => 1,
            "ingredients" => "formaggio fresco spalmabile, confettura di frutti di bosco, zucchero, amido di mais, scorza di limone, uova, panna acida, succo di limone, biscotti digestive, burro, sale",
            "image" => "img/cheescake.jpg",
            "restaurant_id" => [4],
            "category_id" => 2,
        ],
        [
            "name" => "muffin al cioccolato",
            "price" => "4.00",
            "visible" => 1,
            "ingredients" => "formaggio fresco spalmabile, confettura di frutti di bosco, zucchero, amido di mais, scorza di limone, uova, panna acida, succo di limone, biscotti digestive, burro, sale",
            "image" => "img/muffin-al-cioccolato.jpg",
            "restaurant_id" => [4],
            "category_id" => 2,
        ],
        [
            "name" => "torrijas",
            "price" => "11.00",
            "visible" => 1,
            "ingredients" => "pane raffermo, latte, uova, estratto di vaniglia, zucchero, cannella, olio di semi",
            "image" => "img/torrijas.jpg",
            "restaurant_id" => [6],
            "category_id" => 2,
        ],
        [
            "name" => "churros",
            "price" => "4.00",
            "visible" => 1,
            "ingredients" => "formaggio fresco spalmabile, confettura di frutti di bosco, zucchero, amido di mais, scorza di limone, uova, panna acida, succo di limone, biscotti digestive, burro, sale",
            "image" => "img/churros.jpg",
            "restaurant_id" => [6],
            "category_id" => 2,
        ],
        [
            "name" => "alfajores",
            "price" => "8.00",
            "visible" => 1,
            "ingredients" => "fecola di patate, zucchero, uova, bicarbonato di sodio, farina di tipo 00, scorza di limone, burro",
            "image" => "img/alfajores.jpg",
            "restaurant_id" => [7],
            "category_id" => 2,
        ],
        [
            "name" => "bunuelos",
            "price" => "3.50",
            "visible" => 1,
            "ingredients" => "farina di tipo 00, lievito, burro, uova, zucchero, sale, latte, liquore all'anice",
            "image" => "img/bunuelos.jpg",
            "restaurant_id" => [7],
            "category_id" => 2,
        ],
        [
            "name" => "burfi",
            "price" => "2.00",
            "visible" => 1,
            "ingredients" => "burro, latte, farina di cocco, nocciole, mandorle, pistacchi, cardamomo",
            "image" => "img/burfi.jpg",
            "restaurant_id" => [8],
            "category_id" => 2,
        ],
        [
            "name" => "jalebi",
            "price" => "2.50",
            "visible" => 1,
            "ingredients" => "acqua, yogurt greco, farina di tipo 00, cardamomo in polvere, lievito, amido di mais, olio vegetale, zafferano in polvere, succo di limone",
            "image" => "img/jalebi.jpg",
            "restaurant_id" => [8],
            "category_id" => 2,
        ],
        [
            "name" => "baklava",
            "price" => "2.00",
            "visible" => 1,
            "ingredients" => "pasta fillo, burro, mandoorle, cannella in polvere, miele millefiori, zucchero, acqua",
            "image" => "img/baklava.jpg",
            "restaurant_id" => [9],
            "category_id" => 2,
        ],
        [
            "name" => "lokum",
            "price" => "2.50",
            "visible" => 1,
            "ingredients" => "zucchero semolato, succo di limone, gelatina in polvere, zucchero a velo, essenza di rose, acqua, amido di mais, lievito",
            "image" => "img/lokum.jpg",
            "restaurant_id" => [9],
            "category_id" => 2,
        ],
        [
            "name" => "galaktoboureko",
            "price" => "9.00",
            "visible" => 1,
            "ingredients" => "pasta fillo, burro, uova, semolino, zucchero, latte, panna liquida, estratto di vaniglia, miele scorza di limone, cannella in stecche, succo di limone",
            "image" => "img/galaktoboureko.jpg",
            "restaurant_id" => [10],
            "category_id" => 2,
        ],
        [
            "name" => "kourabiedes",
            "price" => "2.50",
            "visible" => 1,
            "ingredients" => "burro, zucchero a velo, tuorlo d'uovo, lievito, farina di tipo 0, mandorle",
            "image" => "img/kourabiedes.jpg",
            "restaurant_id" => [10],
            "category_id" => 2,
        ],
    ],
    "tags" => [
        'vegetarian',
        'vegan',
        'spicy',
        'gluten free',
    ],
    "categories" => [
        "antipasto",
        //1
        "primo",
        //2
        "carne",
        //3
        "pesce",
        //4
        "contorno",
        //5
        "dessert",
        //6
        "pizza",
        //7
        "hamburger",
        //8
        "piadina",
        //9
        "kebab",
        //10
        "fritti",
        //11
        "bibite",
        //12
        "cocktail",
        //13
    ],
];