<?php
return [
    "foods" => [
        [
            "name" => "patatine fritte",
            "price" => "2.90",
            "visible" => 1,
            "ingredients" => "patatine, sale, olio di semi di arachide",
            "image" => "patatine fritte.png",
        ],
        [
            "name" => "bacon burger",
            "price" => "7.10",
            "visible" => 1,
            "ingredients" => "pane, bacon, hamburger, cheddar, maionese, ketchup",
            "image" => "bacon burger.png",
        ],
        [
            "name" => "margherita",
            "price" => "5.50",
            "visible" => 1,
            "ingredients" => "salsa di pomodoro, mozzarella, basilico",
            "image" => "margherita.png",
        ],
        [
            "name" => "napoli",
            "price" => "8.50",
            "visible" => 1,
            "ingredients" => "salsa di pomodoro, mozzarella, acciughe sott'olio, olio, origano",
            "image" => "napoli.png",
        ],
        [
            "name" => "quattro stagioni",
            "price" => "8.00",
            "visible" => 1,
            "ingredients" => "salsa di pomodoro, mozzarella, funghi, carciofi, peperoni, prosciutto cotto",
            "image" => "quattro stagioni.png",
        ],
        [
            "name" => "spaziale",
            "price" => "9.00",
            "visible" => 1,
            "ingredients" => "salsa di pomodoro, mozzarella, patate lesse, gorgonzola, pancetta in cottura, olio, origano",
            "image" => "spaziale.png",
        ],
        [
            "name" => "cornetti pizza",
            "price" => "7.50",
            "visible" => 1,
            "ingredients" => "salsa di pomodoro, mozzarella, olio",
            "image" => "cornetti pizza.png",
        ],
        [
            "name" => "pizzaiola",
            "price" => "8.00",
            "visible" => 1,
            "ingredients" => "salsa di pomodoro, mozzarella, aglio, acciughe, peperoncino, olive, origano",
            "image" => "pizzaiola.png",
        ],
        [
            "name" => "cotechino con lenticchie",
            "price" => "18.00",
            "visible" => 1,
            "ingredients" => "cotechino, lenticchie, carote, olio, rosmarino, sale, sedano cipolle, alloro",
            "image" => "cotechino con lenticchie.png",
        ],
        [
            "name" => "chili con carne",
            "price" => "8.90",
            "visible" => 1,
            "ingredients" => "manzo, peperoni rossi, brodo di carne, cipolle rosse, peperoncino fresco, cumino, zucchero di canna, fagioli, passata di pomodoro, cipolle",
            "image" => "chili con carne.png",
        ],
        [
            "name" => "paella de marisco",
            "price" => "15.60",
            "visible" => 1,
            "ingredients" => "riso bomba, calamari, gamberi, aglio, paprika, passata di pomodoro, olio, pepe, cozze, scampi, cipolle, fumetto di crostacei, zafferano, peperoncini",
            "image" => "paella de marisco.png",
        ],
        [
            "name" => "uramaki di sushi",
            "price" => "7.50",
            "visible" => 1,
            "ingredients" => "salmone, tonno, riso nishiki, aceto di riso, zucchero, acqua, sale, alga kombu",
            "image" => "uramaki di sushi.png",
        ],
        [
            "name" => "zuppa di pesce",
            "price" => "14.90",
            "visible" => 1,
            "ingredients" => "gamberi, gallinella, triglie, aglio, vino bianco, pepe, seppie, coda di rospo, olio, prezzemolo",
            "image" => "zuppa di pesce.png",
        ],
        [
            "name" => "spaghetti di riso con verdure",
            "price" => "8.50",
            "visible" => 1,
            "ingredients" => "spaghetti di riso, zucchine, cipolle, olio, salsa di soia, pepe bianco, carota, sale",
            "image" => "spaghetti di riso con verdure.png",
        ],
        [
            "name" => "parmigiana di patate",
            "price" => "11.00",
            "visible" => 1,
            "ingredients" => "patate, provola, sale, grana, pepe, besciamella",
            "image" => "parmigiana di patate.png",
        ],
        [
            "name" => "fajitas",
            "price" => "5.00",
            "visible" => 1,
            "ingredients" => "tortillas, guacamole, controfiletto di manzo, peperoni rossi, cipolle bianche, worcestershire sauce, cumino, sale, petto di pollo, peperoni, lime, coriandolo, olio",
            "image" => "fajitas.png",
        ],
        [
            "name" => "ramen",
            "price" => "9.00",
            "visible" => 1,
            "ingredients" => "noodles, brodo(acqua, pancia di maiale, zenzero, aglio, katsuobushi, alga kombu, cipollotto), carne di maiale(cotta con tamari, mirin, sake, zenzero, aglio), uovo marinato, cipolle dorate",
            "image" => "ramen.png",
        ],
        [
            "name" => "burrito",
            "price" => "9.00",
            "visible" => 1,
            "ingredients" => "tortilla, macinato di manzo, peperoni rossi, brodo di carne, aglio, coriandolo in polvere, fagioli neri, cipolle rosse, pepe, avocado, lime, mais",
            "image" => "burrito.png",
        ],
        [
            "name" => "empanadas",
            "price" => "7.30",
            "visible" => 1,
            "ingredients" => "impasto, carne bvina, peperoni rossi, olive, strutto, origano, pepe, uova sode, cipolle ramate, cumino",
            "image" => "empanadas.png",
        ],
        [
            "name" => "couscous",
            "price" => "12.10",
            "visible" => 1,
            "ingredients" => "cous cous, brodo vegetale, olio, peperoni rossi, pisellini, pepe, paprika, olio, zucchine, carote, scalogno, scorza di limone",
            "image" => "couscous.png",
        ],
        [
            "name" => "tacos",
            "price" => "8.40",
            "visible" => 1,
            "ingredients" => "tacos, peperoncino dolce, salsiccia, concentrato di pomodore, pepe, pomodori, prezzemolo, olio, cipollotto, panna acida, yogurt",
            "image" => "tacos.png",
        ],
        [
            "name" => "pollo tika masala",
            "price" => "15.50",
            "visible" => 1,
            "ingredients" => "petto di pollo, yogurt greco, garam masala, aglio, sale, zenzero, paprika, panna, aglio, cumino, curcuma",
            "image" => "pollo tika masala.png",
        ],
        [
            "name" => "nachos",
            "price" => "14.30",
            "visible" => 1,
            "ingredients" => "tortillas, peperoncini jalapeno, edamer, olio",
            "image" => "nachos.png",
        ],
        [
            "name" => "baozi",
            "price" => "15.00",
            "visible" => 1,
            "ingredients" => "impasto di farina, maiale, cipollotto, salsa di soia, olio, pepe, cavolo, zenzero, sale",
            "image" => "baozi.png",
        ],
        [
            "name" => "Sprite Vetro",
            "price" => "5.00",
            "visible" => 1,
            "ingredients" => "Bibita Sprite",
            "image" => "https://rs-menus-api.roocdn.com/images/eed0caee-9113-4b7c-82ca-dca20d4ceec6/image.jpeg?width=560&height=315&auto=webp&format=jpg&fit=crop",
        ],
        [
            "name" => "coca-cola",
            "price" => "3.00",
            "visible" => 1,
            "ingredients" => "acqua gassata (o acqua e anidride carbonica), zucchero (saccarosio o sciroppo di saccarosio o sciroppo di mais ad alto contenuto di fruttosio), caffeina, acido fosforico, colorante caramello (E150d), glicerina ed aromi naturali",
            "image" => "https://rs-menus-api.roocdn.com/images/660ad39f-d513-42fc-b27e-8f083d548fdf/image.jpeg?width=543&height=305&auto=webp&format=jpg&fit=crop",
        ],
        [
            "name" => "Sprite",
            "price" => "3.80",
            "visible" => 1,
            "ingredients" => "Bibita Sprite",
            "image" => "https://f.roocdn.com/images/menu_items/19526353/item-image.jpg?width=560&height=315&auto=webp&format=jpg&v=1675186254&fit=crop",
        ],
    ]
];