<?php
return [
    "foods" => [
        [
            "name" => "patatine fritte",
            "price" => "2.90",
            "visible" => 1,
            "ingredients" => "patatine, sale, olio di semi di arachide",
            "image" => "https://rs-menus-api.roocdn.com/images/af746bd6-c814-4508-ae80-951ddecd4a8a/image.jpeg?width=543&height=305&auto=webp&format=jpg&fit=crop",
        ],
        [
            "name" => "bacon burger",
            "price" => "7.10",
            "visible" => 1,
            "ingredients" => "pane, bacon, hamburger, cheddar, maionese, ketchup",
            "image" => "https://rs-menus-api.roocdn.com/images/a9618a3d-ea13-4f45-945c-936b67fd673d/image.jpeg?width=560&height=315&auto=webp&format=jpg&fit=crop",
        ],
        [
            "name" => "coca-cola",
            "price" => "3.00",
            "visible" => 1,
            "ingredients" => "acqua gassata (o acqua e anidride carbonica), zucchero (saccarosio o sciroppo di saccarosio o sciroppo di mais ad alto contenuto di fruttosio), caffeina, acido fosforico, colorante caramello (E150d), glicerina ed aromi naturali",
            "image" => "https://rs-menus-api.roocdn.com/images/660ad39f-d513-42fc-b27e-8f083d548fdf/image.jpeg?width=543&height=305&auto=webp&format=jpg&fit=crop",
        ],
        [
            "name" => "margherita",
            "price" => "5.50",
            "visible" => 1,
            "ingredients" => "salsa di pomodoro, mozzarella, basilico",
            "image" => "https://italianspizza.it/wp-content/uploads/2022/06/FAMILY-PIZZA-MARGHERITA-online-pizza-sconti-eventi-feste-delivery-consegna-a-domicilio-san-colombano-al-lambro-lambrinia-monteleone-lodi-milano-italia.png",
        ],
        [
            "name" => "napoli",
            "price" => "8.50",
            "visible" => 1,
            "ingredients" => "salsa di pomodoro, mozzarella, acciughe sott'olio, olio, origano",
            "image" => "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR6EfKp4WEmv4ED2UzSFHg3Dq86reMHi97FBHMZG7cMJD0zArx7u_opsvoBkwkWo1w4UIs&usqp=CAU",
        ],
        [
            "name" => "quattro stagioni",
            "price" => "8.00",
            "visible" => 1,
            "ingredients" => "salsa di pomodoro, mozzarella, funghi, carciofi, peperoni, prosciutto cotto",
            "image" => "https://upload.wikimedia.org/wikipedia/commons/4/42/Pizza_Quattro_Stagioni_transparent.png?width=858&height=542",
        ],
        [
            "name" => "spaziale",
            "price" => "9.00",
            "visible" => 1,
            "ingredients" => "salsa di pomodoro, mozzarella, patate lesse, gorgonzola, pancetta in cottura, olio, origano",
            "image" => "https://upload.wikimedia.org/wikipedia/commons/4/42/Pizza_Quattro_Stagioni_transparent.png?width=858&height=542",
        ],
        [
            "name" => "prosciutto funghi",
            "price" => "7.50",
            "visible" => 1,
            "ingredients" => "salsa di pomodoro, mozzarella, prosciutto, funghi",
            "image" => "https://banner2.cleanpng.com/20180701/bzg/kisspng-sangria-red-wine-juice-cocktail-tragos-5b386f2fd2ac39.2934068115304251358629.jpg",
        ],
        [
            "name" => "pizzaiola",
            "price" => "8.00",
            "visible" => 1,
            "ingredients" => "salsa di pomodoro, mozzarella, aglio, acciughe, peperoncino, olive, origano",
            "image" => "https://banner2.cleanpng.com/20180701/bzg/kisspng-sangria-red-wine-juice-cocktail-tragos-5b386f2fd2ac39.2934068115304251358629.jpg",
        ],
        [
            "name" => "cotechino con lenticchie",
            "price" => "18.00",
            "visible" => 1,
            "ingredients" => "cotechino, lenticchie, carote, olio, rosmarino, sale, sedano cipolle, alloro",
            "image" => "cotechino con lenticchie.png",
        ],
        [
            "name" => "chili con carne",
            "price" => "8.90",
            "visible" => 1,
            "ingredients" => "manzo, peperoni rossi, brodo di carne, cipolle rosse, peperoncino fresco, cumino, zucchero di canna, fagioli, passata di pomodoro, cipolle",
            "image" => "chili con carne.png",
        ],
        [
            "name" => "paella de marisco",
            "price" => "15.60",
            "visible" => 1,
            "ingredients" => "riso bomba, calamari, gamberi, aglio, paprika, passata di pomodoro, olio, pepe, cozze, scampi, cipolle, fumetto di crostacei, zafferano, peperoncini",
            "image" => "paella de marisco.png",
        ],
        [
            "name" => "uramaki di sushi",
            "price" => "7.50",
            "visible" => 1,
            "ingredients" => "salmone, tonno, riso nishiki, aceto di riso, zucchero, acqua, sale, alga kombu",
            "image" => "uramaki di sushi.png",
        ],
        [
            "name" => "zuppa di pesce",
            "price" => "14.90",
            "visible" => 1,
            "ingredients" => "gamberi, gallinella, triglie, aglio, vino bianco, pepe, seppie, coda di rospo, olio, prezzemolo",
            "image" => "zuppa di pesce.png",
        ],
        [
            "name" => "spaghetti di riso con verdure",
            "price" => "8.50",
            "visible" => 1,
            "ingredients" => "spaghetti di riso, zucchine, cipolle, olio, salsa di soia, pepe bianco, carota, sale",
            "image" => "spaghetti di riso con verdure.png",
        ],
        [
            "name" => "parmigiana di patate",
            "price" => "11.00",
            "visible" => 1,
            "ingredients" => "patate, provola, sale, grana, pepe, besciamella",
            "image" => "parmigiana di patate.png",
        ],
        [
            "name" => "fajitas",
            "price" => "5.00",
            "visible" => 1,
            "ingredients" => "tortillas, guacamole, controfiletto di manzo, peperoni rossi, cipolle bianche, worcestershire sauce, cumino, sale, petto di pollo, peperoni, lime, coriandolo, olio",
            "image" => "fajitas.png",
        ],
        [
            "name" => "ramen",
            "price" => "9.00",
            "visible" => 1,
            "ingredients" => "noodles, brodo(acqua, pancia di maiale, zenzero, aglio, katsuobushi, alga kombu, cipollotto), carne di maiale(cotta con tamari, mirin, sake, zenzero, aglio), uovo marinato, cipolle dorate",
            "image" => "ramen.png",
        ],
        [
            "name" => "Arrotolato Kebab",
            "price" => "6.00",
            "visible" => 1,
            "ingredients" => "Kebab, insalata, pomodoro, salsa piccante, cipolla , salsa yogurt",
            "image" => "https://qualitifood.com/wp-content/uploads/brizy/imgs/piada-kebab-tagliato-545x545x0x68x545x409x1562337866.png",
        ],
        [
            "name" => "Focaccia bianca",
            "price" => "4.00",
            "visible" => 1,
            "ingredients" => "Focaccia bianca",
            "image" => "https://content.dambros.it/uploads/2016/04/19103803/0000121304.jpg",
        ],
        [
            "name" => "Bacon King",
            "price" => "8.10",
            "visible" => 1,
            "ingredients" => "Due hamburger di manzo alla griglia con 8 fette di bacon, cheddar, ketchup e maionese",
            "image" => "https://f.roocdn.com/images/menu_items/19526413/item-image.jpg?width=543&height=305&auto=webp&format=jpg&v=1675186254&fit=crop",
        ],
        [
            "name" => "Sprite",
            "price" => "3.80",
            "visible" => 1,
            "ingredients" => "Bibita Sprite",
            "image" => "https://f.roocdn.com/images/menu_items/19526353/item-image.jpg?width=560&height=315&auto=webp&format=jpg&v=1675186254&fit=crop",
        ],
        [
            "name" => "Bacon king fries con cheddar sauce e bacon bits",
            "price" => "4.40",
            "visible" => 1,
            "ingredients" => "patatine fritte con coriandoli di bacon e salsa cheddar",
            "image" => "https://f.roocdn.com/images/menu_items/182573093/item-image.jpg?width=560&height=315&auto=webp&format=jpg&v=1675186254&fit=crop",
        ],
        [
            "name" => "El Pulled Burrito",
            "price" => "13.50",
            "visible" => 1,
            "ingredients" => "Riso basmati, pulled pork, fagioli rossi, pico de gallo, panna acida e guacamole",
            "image" => "https://rs-menus-api.roocdn.com/images/88b43cfe-184d-4316-a972-7c2353dddb20/image.jpeg?width=560&height=315&auto=webp&format=jpg&fit=crop",
        ],
        [
            "name" => "Taco de Chili",
            "price" => "12.00",
            "visible" => 1,
            "ingredients" => "Base di lattuga, chili con carne, pico de gallo e guacamole",
            "image" => "https://rs-menus-api.roocdn.com/images/b4b78fa1-8c5e-48b7-b277-13ff33082e52/image.jpeg?width=543&height=305&auto=webp&format=jpg&fit=crop",
        ],
        [
            "name" => "Nachos",
            "price" => "7.00",
            "visible" => 1,
            "ingredients" => "Tortillas di mais",
            "image" => "https://rs-menus-api.roocdn.com/images/a68d3915-2e11-4e0a-bdd9-210ec9afd991/image.jpeg?width=560&height=315&auto=webp&format=jpg&fit=crop",
        ],
        [
            "name" => "Manzo con cinque aromi in salsa piccante",
            "price" => "11.00",
            "visible" => 1,
            "ingredients" => "Manzo",
            "image" => "https://rs-menus-api.roocdn.com/images/a68d3915-2e11-4e0a-bdd9-210ec9afd991/image.jpeg?width=560&height=315&auto=webp&format=jpg&fit=crop",
        ],
        [
            "name" => "Ravioli",
            "price" => "6.00",
            "visible" => 1,
            "ingredients" => "Ravioli di maiale",
            "image" => "https://barcalcagno.it/sushi/wp-content/uploads/2019/07/RAVIOLI-R1-R2-.jpg",
        ],
        [
            "name" => "Gamberi",
            "price" => "9.50",
            "visible" => 1,
            "ingredients" => "sale e pepe",
            "image" => "https://www.sushiroyal.it/utenti/sushiroyal/uploads/img_6656.jpg",
        ],
        [
            "name" => "Falafel con salsa allo yogurt",
            "price" => "8.50",
            "visible" => 1,
            "ingredients" => "Falafel tradizionali con salsa allo yogurt",
            "image" => "https://rs-menus-api.roocdn.com/images/4ec0a438-09c0-4b2d-aff6-7e55e0921f0b/image.jpeg?width=560&height=315&auto=webp&format=jpg&fit=crop",
        ],
        [
            "name" => "Pita Gyros Falafel",
            "price" => "13.50",
            "visible" => 1,
            "ingredients" => "Pita con falafel, hummus, pico de gallo, lattuga e salsa",
            "image" => "https://rs-menus-api.roocdn.com/images/28401375-7661-4cdd-a7e5-dc3f2c3d586c/image.jpeg?width=560&height=315&auto=webp&format=jpg&fit=crop",
        ],
        [
            "name" => "Sprite Vetro",
            "price" => "5.00",
            "visible" => 1,
            "ingredients" => "Bibita Sprite",
            "image" => "https://rs-menus-api.roocdn.com/images/eed0caee-9113-4b7c-82ca-dca20d4ceec6/image.jpeg?width=560&height=315&auto=webp&format=jpg&fit=crop",
        ],
    ]
];