<?php
return [
    'resturants' => [
        [
            "name" => "Pizzeria Fuori di Zucca",
            "email" => "pizzeriafuoridizucca@gmail.com",
            "image" => "http://via.placeholder.com/640x360",
            "address" => "Piazza Giuseppe Garibaldi 22, 56126 Pisa (PI)",
            "partita_iva" => "IT46469789712",
            "website" => "www.pizzeriafuoridizucca.it",
            "opening_hours" => "18:00",
            "closing_hours" => "24:00",
            "phone_number" => "3331122334",
        ],
        [
            "name" => "Tai Long Cucina Tipica Cinese",
            "email" => "tailong.chinaresturant@gmail.com",
            "image" => "http://via.placeholder.com/640x360",
            "address" => "borgo Stretto 49, 56126 Pisa (PI)",
            "partita_iva" => "IT46469781111",
            "website" => "www.tailongchinaresturant.it",
            "opening_hours" => "18:00",
            "closing_hours" => "24:00",
            "phone_number" => "3311235813",
        ],
        [
            "name" => "SushiJay Japanese Cuisine",
            "email" => "suhijay@gmail.com",
            "image" => "http://via.placeholder.com/640x360",
            "address" => "via Capponi 69, 56125 Pisa (PI)",
            "partita_iva" => "IT46469782222",
            "website" => "www.suhijay.it",
            "opening_hours" => "18:00",
            "closing_hours" => "24:00",
            "phone_number" => "348 3525758",
        ],
        [
            "name" => "Old Wild West",
            "email" => "oldwildwest@gmail.com",
            "image" => "http://via.placeholder.com/640x360",
            "address" => "Via di Gello 1, 56124 Pisa (PI)",
            "partita_iva" => "IT46469782222",
            "website" => "www.oldwildwest.it",
            "opening_hours" => "18:00",
            "closing_hours" => "24:00",
            "phone_number" => "351 8929384",
        ],
        [
            "name" => "Sollacchero Pisano",
            "email" => "sollaccheropisano@gmail.com",
            "image" => "http://via.placeholder.com/640x360",
            "address" => "Corso Italia 171, 56123 Pisa (PI)",
            "partita_iva" => "IT46469789712",
            "website" => "www.sollaccheropisano.it",
            "opening_hours" => "18:00",
            "closing_hours" => "24:00",
            "phone_number" => "329 1832442",
        ],
    ],
];